// create web server
// 1. load modules
import http from 'http';
import fs from 'fs';
import url from 'url';
import qs from 'querystring';
import template from './lib/template.js';
import path from 'path';
import sanitizeHtml from 'sanitize-html';
import mysql from 'mysql';
